### ISSUE TITLE
Breadcrumb CSS

### ISSUE THREAD

**Issue by edvin** [edvin/tornadofaces#2]
Breadcrumb support has been added to the Ul by adding a `breadcrumb` attribute. The UlRenderer will then add the class `breadcrumb`to the ul element. Markup example:

``` html
<ul class="breadcrumb">
    <li><a href="#">Level One</a></li>
    <li><a href="#">Level Two</a></li>
    <li>Level Three</li>
</ul>
```

Can you add styling to support this?

**Comment by vebjorn** [comment]
I made a push this moment, crude and barebone - but initial!
