### ISSUE TITLE
Default theme.css not loading

### ISSUE THREAD

**Issue by dcardosods** [edvin/tornadofaces#6]
Is it necessary to do any kind of configuration to get the default theme working?

I get a 404 on `.../javax.faces.resource/theme.css.xhtml?ln=tornadofaces-tornado`, but have access to the other resources, e.g. `.../javax.faces.resource/tornadofaces.js?ln=tornadofaces`

**Comment by edvin** [comment]
Hi :) The theme feature is not very streamlined at the moment, I'm sorry. The easiest way right now is to create the folder `src/main/webapp/resources/tornadofaces-tornado` and copy the files from the [default theme](https://github.com/edvin/tornadofaces/tree/master/site/src/main/webapp/resources/tornadofaces-tornado) into it.

I've attached the files so you can simply unpack it and copy to the right location.

The reason I haven't streamlined this is that I don't know of any other users of the framework :) I haven't really told anybody about it but I'm using it in several large commercial projects in my company.

If there is increased interest I'd love to streamline this and other features as well as improve documentation. Please let me know if you run into any issues :)

[tornadofaces-tornado.zip](https://github.com/edvin/tornadofaces/files/322456/tornadofaces-tornado.zip)

**Comment by dcardosods** [comment]
So, I still can't make it to work. 
I built a `theme.css` from the SASS files and copied all the files into `WebContent/WEB-INF/resources/tornadofaces-tornado`. I also tried http://stackoverflow.com/questions/8320486/structure-for-multiple-jsf-projects-with-shared-code/8320738#8320738, but without success.

ps: I am a newbie with JSF.

**Comment by edvin** [comment]
Your problem is most likely that you're copying the files into WebContent/WEB-INF/resources, but it's supposed to go in WebContent/resources :) Does that resolve the issue?

**Comment by dcardosods** [comment]
I had tried that.
I found the problem. In my web.xml I had

```
<servlet-mapping>
        <servlet-name>Faces Servlet</servlet-name>
        <url-pattern>/faces/*</url-pattern>
    </servlet-mapping>
```

changing to 

```
<servlet-mapping>
        <servlet-name>Faces Servlet</servlet-name>
        <url-pattern>*.xhtml</url-pattern>
    </servlet-mapping>
```

makes it work.

btw, the `.js` files of tornado faces where put correctly under `faces/*`, only the theme wasn't.

Thanks for your help :)

**Comment by edvin** [comment]
Great that you figured it out :) OK, I'll close the issue.
